//! Short and uniform sampling for NERV-Seal (WP §6.3.1, §6.3.7, §6.3.8).
//!
//! * Uniform: A ∈ R^{8×8} is XOF-expanded from a 32-byte public seed under
//!   `nerv.seal` — row-major, u32-LE draws rejected above Q for exact
//!   uniformity. Anyone re-derives A bit-for-bit; the seed is the wire
//!   object, never the matrix (erratum 21).
//! * Short: r, e₁, e₂ are CBD(η = 2) — 4 bits per coefficient, value
//!   b₀ + b₁ − b₂ − b₃ — from XOF streams under `nerv.seal.noise`
//!   (per-leg wallet seed; frozen order r ‖ e₁ ‖ e₂).
//! * Bounds: every sampled coefficient is rejection-checked against ±3σ
//!   (= ±3 at η = 2, σ = 1) — the circuit's statement-10 smallness bound.
//!   At frozen parameters the CBD support is [−2, 2] ⊂ [−3, 3], so the
//!   rejection is a verified no-op; the machinery exists for parameter
//!   evolution and is the same bound the AIR enforces (P9: stated, not
//!   hidden). Attempt caps keep every sampler total (uniform per-matrix
//!   cap-exhaust probability < 2^−2000).

use nerv_core::constants::{SEAL, SEAL_NOISE};
use nerv_core::hash::Xof;
use crate::error::SealError;
use crate::ring::{Mat8x8, Poly, Vec2, Vec8, N, Q};

/// CBD parameter η (WP §6.3.8).
pub const ETA: u32 = 2;
/// The smallness bound ±3σ (σ = 1 at η = 2) — statement 10's range check.
pub const NOISE_BOUND: u64 = 3;

const CBD_BYTES_PER_POLY: usize = 128;
const _: () = assert!(CBD_BYTES_PER_POLY * 8 == N * 2 * ETA as usize);
const UNIFORM_ATTEMPT_CAP: u32 = 1024;
const SHORT_ATTEMPT_CAP: u32 = 1024;

/// The 32-byte seed from which the epoch public matrix A is expanded.
/// Generated and committed by the DKG (chunk 9); public.
#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
pub struct ASeed([u8; 32]);

impl ASeed {
    pub fn from_bytes(bytes: [u8; 32]) -> Self {
        ASeed(bytes)
    }

    pub fn as_bytes(&self) -> &[u8; 32] {
        &self.0
    }
}

/// The 32-byte per-leg seed from which a wallet deterministically derives
/// its sealing randomness (r, e₁, e₂). Fresh per leg; generated by the
/// wallet's own entropy source.
#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
pub struct NoiseSeed([u8; 32]);

impl NoiseSeed {
    pub fn from_bytes(bytes: [u8; 32]) -> Self {
        NoiseSeed(bytes)
    }

    pub fn as_bytes(&self) -> &[u8; 32] {
        &self.0
    }
}

impl nerv_core::codec::Encode for NoiseSeed {
    fn encode_into(&self, out: &mut Vec<u8>) {
        out.extend_from_slice(&self.0);
    }
    fn encoded_len(&self) -> usize {
        32
    }
}

impl nerv_core::codec::Decode for NoiseSeed {
    fn decode_from(r: &mut nerv_core::codec::Reader<'_>) -> Result<Self, nerv_core::error::CodecError> {
        Ok(NoiseSeed(r.take_array::<32>()?))
    }
}

fn cbd2_block(bytes: &[u8; CBD_BYTES_PER_POLY]) -> [i64; N] {
    let mut vals = [0i64; N];
    for (j, v) in vals.iter_mut().enumerate() {
        let nib = if j % 2 == 0 { bytes[j / 2] & 0x0F } else { bytes[j / 2] >> 4 };
        *v = (nib & 1) as i64
            + ((nib >> 1) & 1) as i64
            - ((nib >> 2) & 1) as i64
            - ((nib >> 3) & 1) as i64;
    }
    vals
}

fn within_bound(vals: &[i64; N]) -> bool {
    vals.iter().all(|&v| v.unsigned_abs() <= NOISE_BOUND)
}

/// One CBD(η = 2) polynomial from the stream, rejection-checked against
/// ±NOISE_BOUND; a rejected block is discarded and the next 128 stream
/// bytes consumed (a no-op at frozen η — module docs).
pub fn sample_short_poly(xof: &mut Xof) -> Result<Poly, SealError> {
    for _ in 0..SHORT_ATTEMPT_CAP {
        let vals = cbd2_block(&xof.read_array::<CBD_BYTES_PER_POLY>());
        if within_bound(&vals) {
            return Ok(Poly::from_centered(&vals));
        }
    }
    Err(SealError::SamplingExhausted { attempts: SHORT_ATTEMPT_CAP as u64 })
}

pub fn sample_short_vec8(xof: &mut Xof) -> Result<Vec8, SealError> {
    let mut v = [Poly::zero(); 8];
    for p in v.iter_mut() {
        *p = sample_short_poly(xof)?;
    }
    Ok(Vec8::new(v))
}

pub fn sample_short_vec2(xof: &mut Xof) -> Result<Vec2, SealError> {
    let mut v = [Poly::zero(); 2];
    for p in v.iter_mut() {
        *p = sample_short_poly(xof)?;
    }
    Ok(Vec2::new(v))
}

/// The wallet's per-leg sealing randomness, derived in the frozen order
/// r ‖ e₁ ‖ e₂ from one stream. Deterministic in the seed (conformance
/// vectors pin it); fresh per leg by wallet policy.
pub fn derive_short_triplet(seed: &NoiseSeed) -> Result<(Vec8, Vec8, Vec2), SealError> {
    let mut xof = Xof::new(&SEAL_NOISE, seed.as_bytes());
    let r = sample_short_vec8(&mut xof)?;
    let e1 = sample_short_vec8(&mut xof)?;
    let e2 = sample_short_vec2(&mut xof)?;
    Ok((r, e1, e2))
}

/// One uniform polynomial: u32-LE draws, rejected ≥ Q (exact uniformity on
/// [0, Q); ~1.33 draws per coefficient).
pub fn sample_uniform_poly(xof: &mut Xof) -> Result<Poly, SealError> {
    let mut a = [0u64; N];
    for c in a.iter_mut() {
        let mut done = false;
        for _ in 0..UNIFORM_ATTEMPT_CAP {
            let raw = u64::from(u32::from_le_bytes(xof.read_array::<4>()));
            if raw < Q {
                *c = raw;
                done = true;
                break;
            }
        }
        if !done {
            return Err(SealError::SamplingExhausted { attempts: UNIFORM_ATTEMPT_CAP as u64 });
        }
    }
    Ok(Poly::new(a))
}

/// A = XOF("nerv.seal", seed), row-major (row, column, coefficient order).
/// Deterministic; the DKG transcript commits the seed and anyone verifies
/// the expansion.
pub fn expand_matrix(seed: &ASeed) -> Result<Mat8x8, SealError> {
    let mut xof = Xof::new(&SEAL, seed.as_bytes());
    let mut rows = [[Poly::zero(); 8]; 8];
    for row in rows.iter_mut() {
        for p in row.iter_mut() {
            *p = sample_uniform_poly(&mut xof)?;
        }
    }
    Ok(Mat8x8::new(rows))
}

/// Ternary CBD(η = 1): coefficient b₀ − b₁ ∈ {−1, 0, 1}, 2 bits per
/// coefficient, 64 bytes per polynomial — the DKG's committee-noise
/// distribution (erratum 40/41). Infallible.
pub fn sample_ternary_poly(xof: &mut Xof) -> Poly {
    let bytes = xof.read_array::<64>();
    let mut vals = [0i64; N];
    for (j, v) in vals.iter_mut().enumerate() {
        let bits = (bytes[j / 4] >> ((j % 4) * 2)) & 3;
        *v = (bits & 1) as i64 - ((bits >> 1) & 1) as i64;
    }
    Poly::from_centered(&vals)
}

pub fn sample_ternary_vec8(xof: &mut Xof) -> Vec8 {
    let mut v = [Poly::zero(); 8];
    for p in v.iter_mut() {
        *p = sample_ternary_poly(xof);
    }
    Vec8::new(v)
}



#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    fn splitmix64(state: &mut u64) -> u64 {
        *state = state.wrapping_add(0x9E37_79B9_7F4A_7C15);
        let mut z = *state;
        z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
        z ^ (z >> 31)
    }

    #[test]
    fn cbd2_block_decodes_nibbles() {
        let mut bytes = [0u8; 128];
        bytes[0] = 0x1B;
        bytes[1] = 0x0F;
        bytes[127] = 0x2C;
        let v = cbd2_block(&bytes);
        assert_eq!(v[0], 1);
        assert_eq!(v[1], -1);
        assert_eq!(v[2], 0);
        assert_eq!(v[3], 0);
        assert_eq!(v[254], -2);
        assert_eq!(v[255], 1);
    }

    #[test]
    fn noise_bound_predicate() {
        let mk = |x: i64| {
            let mut a = [0i64; N];
            a[0] = x;
            a
        };
        assert!(within_bound(&mk(0)));
        assert!(within_bound(&mk(2)));
        assert!(within_bound(&mk(-2)));
        assert!(within_bound(&mk(3)));
        assert!(within_bound(&mk(-3)));
        assert!(!within_bound(&mk(4)));
        assert!(!within_bound(&mk(-4)));
    }

    #[test]
    fn short_poly_pin_matches_manual_nibble_decode() {
        let seed = NoiseSeed::from_bytes([0x7A; 32]);
        let mut x1 = Xof::new(&SEAL_NOISE, seed.as_bytes());
        let raw = x1.read_array::<CBD_BYTES_PER_POLY>();
        let mut expect = [0i64; N];
        for j in 0..N {
            let nib = if j % 2 == 0 { raw[j / 2] & 0x0F } else { raw[j / 2] >> 4 };
            expect[j] = (nib & 1) as i64
                + ((nib >> 1) & 1) as i64
                - ((nib >> 2) & 1) as i64
                - ((nib >> 3) & 1) as i64;
        }
        let mut x2 = Xof::new(&SEAL_NOISE, seed.as_bytes());
        assert_eq!(sample_short_poly(&mut x2).unwrap(), Poly::from_centered(&expect));
        assert_eq!(x2.position(), 128);
    }

    #[test]
    fn cbd2_distribution_matches_binomial() {
        // T = 51,200 coefficients; expected C(4, v+2)/16 per value;
        // 6σ tolerances precomputed (σ = 54.8 / 98.0 / 109.5).
        let mut x = Xof::new(&SEAL_NOISE, b"distribution");
        let mut counts = [0u64; 5];
        for _ in 0..200 {
            let p = sample_short_poly(&mut x).unwrap();
            for v in p.centerlift() {
                counts[(v + 2) as usize] += 1;
            }
        }
        let bands = [(3200, 330), (12800, 590), (19200, 660), (12800, 590), (3200, 330)];
        for (i, &(mean, tol)) in bands.iter().enumerate() {
            assert!(
                counts[i].abs_diff(mean) <= tol,
                "value {} count {}",
                i as i64 - 2,
                counts[i]
            );
        }
    }

    #[test]
    fn triplet_deterministic_bounded_distinct() {
        let seed = NoiseSeed::from_bytes([0x5E; 32]);
        let (r1, e11, e21) = derive_short_triplet(&seed).unwrap();
        let (r2, e12, e22) = derive_short_triplet(&seed).unwrap();
        assert_eq!(r1, r2);
        assert_eq!(e11, e12);
        assert_eq!(e21, e22);
        for p in r1.polys().iter().chain(e11.polys().iter()).chain(e21.polys().iter()) {
            for v in p.centerlift() {
                assert!(v >= -2 && v <= 2);
            }
        }
        assert_ne!(r1, e11);
        let (r3, _, _) = derive_short_triplet(&NoiseSeed::from_bytes([0x5F; 32])).unwrap();
        assert_ne!(r1, r3);
    }

    #[test]
    fn expand_matrix_deterministic_seed_sensitive_reduced() {
        let a = expand_matrix(&ASeed::from_bytes([1; 32])).unwrap();
        assert_eq!(a, expand_matrix(&ASeed::from_bytes([1; 32])).unwrap());
        assert_ne!(a, expand_matrix(&ASeed::from_bytes([2; 32])).unwrap());
        for row in a.rows() {
            for p in row {
                for &c in p.coefficients() {
                    assert!(c < Q);
                }
            }
        }
    }

    #[test]
    fn expand_matrix_pin_matches_manual_rejection_stream() {
        let seed = ASeed::from_bytes([0x33; 32]);
        let m = expand_matrix(&seed).unwrap();
        let mut x = Xof::new(&SEAL, seed.as_bytes());
        for i in 0..8 {
            for j in 0..8 {
                for c in 0..N {
                    let v = loop {
                        let raw = u32::from_le_bytes(x.read_array::<4>());
                        if u64::from(raw) < Q {
                            break u64::from(raw);
                        }
                    };
                    assert_eq!(m.row(i)[j].coefficient(c), v);
                }
            }
        }
    }

    #[test]
    fn expand_matrix_uniform_in_quartiles() {
        // 16,384 coefficients; 4,096 expected per quartile; σ = 55.4 → 6σ
        // tolerance 340 (integer-only by precomputation).
        let m = expand_matrix(&ASeed::from_bytes([0x11; 32])).unwrap();
        let (q1, q2, q3) = (Q / 4, Q / 2, 3 * Q / 4);
        let mut counts = [0u64; 4];
        for row in m.rows() {
            for p in row {
                for &c in p.coefficients() {
                    let b = if c < q1 { 0 } else if c < q2 { 1 } else if c < q3 { 2 } else { 3 };
                    counts[b] += 1;
                }
            }
        }
        for &n in counts.iter() {
            assert!(n.abs_diff(4096) <= 340, "quartile count {n}");
        }
    }

    proptest! {
        #[test]
        fn prop_triplet_deterministic_and_in_support(seed in any::<u64>()) {
            let mut b = [0u8; 32];
            b[..8].copy_from_slice(&seed.to_le_bytes());
            let ns = NoiseSeed::from_bytes(b);
            let (r, e1, e2) = derive_short_triplet(&ns).unwrap();
            let (r2, e12, e22) = derive_short_triplet(&ns).unwrap();
            prop_assert_eq!(r, r2);
            prop_assert_eq!(e1, e12);
            prop_assert_eq!(e2, e22);
            for p in r.polys().iter().chain(e1.polys().iter()).chain(e2.polys().iter()) {
                for v in p.centerlift() {
                    prop_assert!(v >= -2 && v <= 2);
                }
            }
        }
    }

    #[test]
    fn seed_types_roundtrip() {
        let mut s = 0xABCDu64;
        let mut b = [0u8; 32];
        for ch in b.chunks_mut(8) {
            ch.copy_from_slice(&splitmix64(&mut s).to_le_bytes());
        }
        assert_eq!(ASeed::from_bytes(b).as_bytes(), &b);
        assert_eq!(NoiseSeed::from_bytes(b).as_bytes(), &b);
        assert_ne!(ASeed::from_bytes(b), ASeed::from_bytes([0; 32]));
    }

     #[test]
    fn ternary_sampler_support_and_pin() {
        let mut x = Xof::new(&SEAL_NOISE, b"ternary pin");
        let raw = x.read_array::<64>();
        let mut expect = [0i64; 256];
        for j in 0..256 {
            let bits = (raw[j / 4] >> ((j % 4) * 2)) & 3;
            expect[j] = (bits & 1) as i64 - ((bits >> 1) & 1) as i64;
        }
        let mut x2 = Xof::new(&SEAL_NOISE, b"ternary pin");
        assert_eq!(sample_ternary_poly(&mut x2), Poly::from_centered(&expect));
        assert_eq!(x2.position(), 64);
        let v = sample_ternary_vec8(&mut x2);
        assert_eq!(x2.position(), 64 + 8 * 64);
        for p in v.polys() {
            for c in p.centerlift() {
                assert!(c >= -1 && c <= 1);
            }
        }
    }


}
